### PR TITLE
Return descriptive and comparable errors

### PR DESCRIPTION
**Pull request by jghiloni**
There are situations in my use case where I need to be able to tell if `Get` is erroring because it can't find the key (a case I want to ignore) or for some other reason (that I do not want to ignore). 

I've developed this in such a way that no error messages have changed and all existing tests pass. This should introduce no changes to how folks are using it now if they don't want to change.

### CODE REVIEW

**Comment by jghiloni** [comment]
It's the same except now you need Go 1.13+ to test 😬

**Comment by jghiloni** [comment]
do we need to test as far back as 1.7? 

Edit: i think i have a fix in mind, I'll add it

**Review by mitchellh — COMMENTED** [review]
This looks good! I don't think we need to support before Go 1.13 so if you want to revert that commit I'd be fine bumping the requirements up.

**Comment by jghiloni** [comment]
Well I've got everything working now way far back to 1.7, so happy to leave it as is for any legacy users

**Comment by jghiloni** [comment]
will leave that choice up to you, happy to revert if you'd rather that for code cleanliness

**Comment by jghiloni** [comment]
@mitchellh I will revert that commit and bump your travis.yml so it's only testing 1.13 and tip

**Comment by jghiloni** [comment]
Hi @mitchellh! Has there been any movement on this? Thanks!

**Comment by jghiloni** [comment]
Hi folks! This sure would be nice to have, any chance we could get it merged in?

**Comment by mitchellh** [comment]
Sorry I dropped this! Merging.

**Comment by jghiloni** [comment]
thanks! 🙏

**Pull request merged**
